name: Deploy

on: push

jobs:
    build:
        runs-on: ${{matrix.os}}

        # services:
        #     redis:
        #         image: redis
        #         ports:
        #             - 6379:6379

        strategy:
          matrix:
            os: [ ubuntu-latest]
            node: [ 18]

        steps:
            # - name: Install redis cli
            #   run: sudo apt-get update -y && sudo apt-get install redis-tools -y

            # - name: Test redis
            #   run: redis-cli -h localhost -p 6379 ping


            # - name: Print Variable
            #   run: echo "${{env.SECRET}}"

            - name: Checkout
              uses: actions/checkout@v4

            - name: setup
              uses: digi-fry/setup-yarn-node-action@v1
              with:
                node-version: ${{matrix.node}}

            - name: Instalar dependencias
              run: yarn install

            # - name: Test
            #   run: yarn test

            - name: Build page
              run: yarn build

            - name: Upload Artefact
              if: ${{matrix.os == 'ubuntu-latest' && matrix.node == 18}}
              uses: actions/upload-pages-artifact@v3
              with:
                path: build/


    deploy:
        needs: build
        runs-on: ubuntu-latest

        permissions: 
            pages: write
            id-token: write

        environment: 
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url}}

        steps:
          - name: Deploy
            id: deployment
            uses: actions/deploy-pages@v4
            
              

    # notify:
    #     runs-on: ubuntu-latest
    #     needs: deploy
    #     if: always()

    #     steps:
    #       - name: Notificar to stack
    #         uses: 8398a7/action-slack@v3
    #         env: 
    #             SLACK_WEBHOOK_URL: ${{secrets.SLACK}}

    #         with:
              
              
             
