name: Deploy

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        # services:
        #     redis:
        #         image: redis
        #         ports:
        #             - 6379:6379

        steps:
            # - name: Install redis cli
            #   run: sudo apt-get update -y && sudo apt-get install redis-tools -y

            # - name: Test redis
            #   run: redis-cli -h localhost -p 6379 ping


            # - name: Print Variable
            #   run: echo "${{env.SECRET}}"

            - name: Checkout
              uses: actions/checkout@v4

            - name: setup
              uses: actions/setup-node@v4
              with:
                node-version: '18'

            # - name: Instalar dependencias
            #   run: yarn install

            # - name: Test
            #   run: yarn test

            - name: Yarn Setup
              uses: DerYeger/yarn-setup-action@master
              with:
                node-version: 18

            - name: Build page
              run: yarn build

            - name: Upload Artefact
              uses: actions/upload-pages-artifact@v3
              with:
                path: public/


    deploy:
        needs: build
        runs-on: ubuntu-latest

        permissions: 
            pages: write
            id-token: write

        environment: 
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url}}

        steps:
          - name: Deploy
            id: deployment
            uses: actions/deploy-pages@v4
              
             